config/routes.rb
Missioncontrol::Application.routes.draw do
  root :to => "homes#index"

  resources :accounts
  resources :homes
end

app/models/account.rb
class Account < ActiveRecord::Base
  attr_accessible :account_type, :token
end

app/models/pivotal.rb
class Pivotal
  PROJECTS = YAML.load(File.open("#{Rails.root}/config/pivotal_projects.yml", "r"))

  # connect
  # connects to the Pivotal Tracker account
  # @author Jason Truluck
  def self.connect
    PivotalTracker::Client.use_ssl = true
    PivotalTracker::Client.token = Account.find_by_account_type("pivotal").token
  end
  # activity_feed
  # returns the activity feed for all projects
  # @author Jason Truluck
  def self.activity_feed
    connect
    PivotalTracker::Activity.all
  end

  # activity_feed_for
  # returns the activity feed to the defined project
  # @param [Integer] project_id the project id for the project being queried
  # @author Jason Truluck
  def self.activity_feed_for(project_id)
    connect
    project = PivotalTracker::Project.find(project_id)
    project.activities.all
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.all
  end

  def show
    @account = Account.find(params[:id])
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(params[:account])
    if @account.save
      redirect_to @account, :notice => "Successfully created account."
    else
      render :action => 'new'
    end
  end

  def edit
    @account = Account.find(params[:id])
  end

  def update
    @account = Account.find(params[:id])
    if @account.update_attributes(params[:account])
      redirect_to @account, :notice  => "Successfully updated account."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @account = Account.find(params[:id])
    @account.destroy
    redirect_to accounts_url, :notice => "Successfully destroyed account."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index

  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<%= form_for @account do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :account_type %><br />
    <%= f.text_field :account_type %>
  </p>
  <p>
    <%= f.label :token %><br />
    <%= f.text_field :token %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/accounts/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Show", @account %> |
  <%= link_to "View All", accounts_path %>
</p>

app/views/accounts/index.html.erb
<table>
  <tr>
    <th>Account Type</th>
    <th>Token</th>
  </tr>
  <% for account in @accounts %>
    <tr>
      <td><%= account.account_type %></td>
      <td><%= account.token %></td>
      <td><%= link_to "Show", account %></td>
      <td><%= link_to "Edit", edit_account_path(account) %></td>
      <td><%= link_to "Destroy", account, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Account", new_account_path %></p>

app/views/accounts/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back to List", accounts_path %></p>

app/views/accounts/show.html.erb
<p>
  <strong>Account Type:</strong>
  <%= @account.account_type %>
</p>
<p>
  <strong>Token:</strong>
  <%= @account.token %>
</p>

<p>
  <%= link_to "Edit", edit_account_path(@account) %> |
  <%= link_to "Destroy", @account, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", accounts_path %>
</p>

app/views/homes/index.html.erb
The home controller index

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Missioncontrol</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>